### ISSUE TITLE
Affichage des récompenses pas claires

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#12]
J'ai mis du temps à comprendre.

![image](https://user-images.githubusercontent.com/49441994/151832812-92e2c6ae-aa8c-4f02-89a0-7fbf0697f6eb.png)

Il faut surement revoir la police et peut être préférer une icon pour séparer les deux places ?

**Comment by Arthurooooo** [comment]
Tu suggères quoi comme icone?

**Comment by wandyou** [comment]
https://github.com/Arthurooooo/qeels.io/issues/10#issuecomment-1027045431
