### ISSUE TITLE
Nombre de vue pas clair

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#14]
![image](https://user-images.githubusercontent.com/49441994/151833080-b4839bde-751f-4ca6-abe5-273c4b8f7be7.png)

Je n'avais pas compris que le chiffre représentait le nombre de vues, je pensais que c'était peut être le nombre de vidéos sur le compte ou jsp. Ajouter "vues" serait plus clair

**Comment by Arthurooooo** [comment]
Est-ce que tu trouves ca + clair mnt?

**Comment by wandyou** [comment]
Oui
