### ISSUE TITLE
Lien visités n'ont plus leur aspect "cliquable"

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#15]
![image](https://user-images.githubusercontent.com/49441994/151833579-2830fc1c-bd30-4c37-9e8c-d26bbbf7271e.png)

Une fois qu'on a visité un des deux liens sur la capture, alors ils apparaissent comme le texte classique (mais sont encore cliquables)

**Comment by Arthurooooo** [comment]
On a mis un "Clique ici" pour que ca soit + explicite
