### ISSUE TITLE
Modal parrainage pas du tout fonctionnel

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#16]
![image](https://user-images.githubusercontent.com/49441994/151833948-22dadbc8-bbbf-4df8-bf11-87e76b8057b4.png)

Le clic sur les boutons est impossible, le formulaire n'apparait pas.

**Comment by Arthurooooo** [comment]
J'ai fait disparaitre l'option de voir cette popup quand t pas connecté #efficace
