### ISSUE TITLE
"Obtenir lien de parrainage" ne fonctionne pas du tout

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#17]
![image](https://user-images.githubusercontent.com/49441994/151834136-8d6daec2-5cc1-41e1-8514-00083ecb7488.png)

Il redirige vers cette page (https://qeels.io/invite?code=) avec "Oops" dans le titre.

C'est une page pas finie on dirait. Le footer n'est du coup pas du tout le bon.
C'est une fonctionnalité critique là je pense puisqu'elle permet de gagner plus d'agent, beaucoup vont cliquer dessus.

**Comment by Arthurooooo** [comment]
Tu étais déconnecté  en cliquant sur le bouton

**Comment by wandyou** [comment]
Oui du coup la page devrait être inaccessible si on est déconnecté / rediriger vers la dernière URL visitée connue

**Comment by Arthurooooo** [comment]
C'est fait! Ils sont désormais redirigés vers index
