### ISSUE TITLE
Mauvaises dénomination dans le profil

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#20]
![image](https://user-images.githubusercontent.com/49441994/151844366-21d6dd5e-c3ba-41de-9135-66f917db9453.png)

Dans mon profil on dit "Prénom" alors qu'à l'inscription on a demandé mon "pseudo"

**Comment by Arthurooooo** [comment]
C'est changé, ca apparaitra dans la MAJ de ce midi
