### ISSUE TITLE
Ordre d'affichage des challenges différents

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#22]
Sur la page d'accueil : 
![image](https://user-images.githubusercontent.com/49441994/151844819-d2983774-523c-4d0c-bc93-bbac0d516eb3.png)

Sur la page des challenges :
![image](https://user-images.githubusercontent.com/49441994/151844862-ad269991-0e23-4925-92c4-6116cdc30ce9.png)

Pourtant sur cette dernière, les filtres ne font rien

**Comment by Arthurooooo** [comment]
Les filtres marchent, mais le hasard a fait que ces 3 compétitions apparaissent dans le même ordre avec ces 2 filtres
