### ISSUE TITLE
Tooltip vide à l'affichage à la submission des liens tiktok quand tout est ok (que y'a un lien, que les CGU sont cochés, et que je suis connecté)

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#23]
![image](https://user-images.githubusercontent.com/49441994/151845132-39985c14-e9d4-48b0-85d4-37f1a68c32a5.png)

**Comment by Arthurooooo** [comment]
Corrigé aussi, ca arrive dans la MAJ de ce midi
