### ISSUE TITLE
Aucune vérification lors de la participation

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#25]
J'ai pu poster une vidéo tiktok avec un autre son et y'a pas eu de soucis

**Comment by Arthurooooo** [comment]
En effet, on a pas encore trouvé de moyen de vérifier ça.

**Comment by wandyou** [comment]
https://tikapi.io/documentation/#operation/uservideo

Une API non officielle mais avec une version gratuite, elle a l'air de fournir les infos que tu pourrais utiliser + beaucoup d'autres

![Capture d’écran 2022-02-01 à 13 03 01](https://user-images.githubusercontent.com/49441994/151965157-88f9a1d4-d362-4a04-b641-ef8dc88b891a.png)
