### ISSUE TITLE
URGENT écran blanc 

### ISSUE THREAD

**Issue by thomas-denizot** [Arthurooooo/qeels.io#36]
Quand on clique sur confirmer mon email c'est toujours écran blanc et email non confirmé. C'est important pour l'expérience de nos users que ça fasse plus ça on peut en perdre beaucoup comme ça

**Comment by Arthurooooo** [comment]
Je te confirme que la page marche très bien. C'est juste que quand tu fais le test depuis la version dev, le mail te redirige tout de même vers la version live. La version live ne trouvant pas ton token (puisqu'il vient de la version dev), le temps de recherche de ton profil dans la base de données est très long (puisqu'il cherche un token qu'il ne trouvera jamais) mais ca finit toujours par rediriger au final
