### ISSUE TITLE
Vidéo non centrée desktop

### ISSUE THREAD

**Issue by thomas-denizot** [Arthurooooo/qeels.io#38]
La vidéo est collée en haut et n'est pas centrée par rapport au bandeau noir (voir "minutes de calme intérieur) sur development

**Comment by Arthurooooo** [comment]
C'est parce que le format de la vidéo a changé par rapport à ce que j'avais prévu. Il me faut un format vidéo standard qui change pas, donc let me know lequel

**Comment by Arthurooooo** [comment]
(par format j'entend ratio longueur/largeur)
