### ISSUE TITLE
Liens sociaux footer mal faits

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#5]
![image](https://user-images.githubusercontent.com/49441994/151830200-b77dfa36-2023-467f-ab4e-699592e239db.png)

On ne peux pas ouvrir dans un nouvel onglet (ni en maintenant command, ni avec le clic de la molette, ni avec clic droit ouvrir dans un nouvel onglet). J'imagine que Bubble fait une mauvaise intégration de ça.

Du coup pour des liens sociaux, et de manière générale pour des liens qui te font sortir du domaine actuel, je recommande de mettre automatiquement l'ouverture d'un nouvel onglet.

**Comment by Arthurooooo** [comment]
Ouverture auto dans nouvel onglet, je push ca soon
