### ISSUE TITLE
Le logo ne ramène pas à la page d'accueil dans le footer

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#6]
![image](https://user-images.githubusercontent.com/49441994/151830538-ef23595e-67bd-4ce7-815e-0caba8552efe.png)

Par convention, on s'attend souvent à ce qu'un clic sur le logo de la boite / marque / app redirige vers l'accueil. Sur le logo du footer ce n'est pas le cas

**Comment by Arthurooooo** [comment]
Fait ✅
