### ISSUE TITLE
Envoi de lien tiktok quand on est pas connecté pas fou

### ISSUE THREAD

**Issue by wandyou** [Arthurooooo/qeels.io#9]
![Capture d’écran 2022-01-31 à 17 23 10](https://user-images.githubusercontent.com/49441994/151832093-8f299c2a-e712-4b20-9f61-6ae8b25baf8f.png)

J'ai ajouté un lien car rien ne m'indiquait que je devais être connecté.
Puis au moment de cliquer il m'a dit que je dois me connecter d'abord.

Ce serait peut être mieux de ne pas afficher le formulaire si on est pas encore connecté, ou alors de faire pointer le bouton vers le form de connexion, tout en gardant en mémoire sa participation à ce challenge

**Comment by Arthurooooo** [comment]
On a pas de form de connexion mais juste le bout "Login with TikTok", qu'est-ce que tu recommande?

**Comment by wandyou** [comment]
Imaginons qu'on nomme ton bloc d'insertion de lien "ajout-lien-tiktok" alors on pourrait imaginer : 

`if (user->notConnected) { hide "ajout-lien-tiktok" }`

ou mieux : `if (user->connected) { show "ajout-lien-tiktok" }`

2ème Variante un peu mieux :
Tu laisses le titre "Insère ton lien TikTok ci-dessous" et tout le reste, mais à la place du champ de texte + le bouton + les CGU : `if (user->notConnected) { hide "ajout-lien-tiktok"; show "login-with-tiktok-btn"; }`

3ème Variante encore mieux :
Tu fais comme au dessus sauf que tu laisses le champ de texte, mais si l'utilisateur est connecté alors il y a le bouton "ok", si l'utilisateur n'est pas connecté il y a le bouton "Login with Tiktok", sauf que particularité, s'il clique dessus, d'abord tu génères un cookie avec le lien qu'il a renseigné, puis tu lui fait faire le flow de connexion habituel. Suite à sa connexion, si le dashboard détecte un cookie qui correspond à une participation non aboutie, il la traite et supprime le cookie

**Comment by Arthurooooo** [comment]
Un peu moche de mettre Login with TikTok aussi long sur le bouton non?

la 3eme option est cool, faudrait que je mette en place ce système de cookies mais en l’état du parcours de signup, je considère pas un user comme user tant qu'il a pas input son email donc pas possible de mettre une participation à ce moment-la.. (si il quitte le site avant d'input son email c relou)

**Comment by wandyou** [comment]
Je vois pas le problème avec la 3ème option, le cookie disparait jamais. Donc dès que tu as l'event "connexion user réussie", tu vérifies si un cookie existe, si oui tu continues le process de participation, si non, tu fais rien.

**Comment by Arthurooooo** [comment]
Compliqué à faire avec Bubble le système de cookies, mais j'ai un peu modifié. Mnt y'a des tooltips, t'en penses quoi?

**Comment by wandyou** [comment]
Que y'a pas de challenges ouverts donc que je peux pas tester encore, mais si c'est le mieux que tu puisses faire ... De toute façon ce sera mieux que rien.
